-- QR 로 붙는 폰은 로그인 상태가 아니다. PC(로그인)가 만든 단기 세션의 sessionId 로
-- 폰이 붙고, 그 세션에서만 통하는 sessionToken 으로 이후 요청을 인증한다.
-- sessionId 는 추측 불가능해야 하므로 순번이 아니라 UUID 를 공개 식별자로 쓴다.
--   CREATED    PC 가 세션을 만들었고 아직 폰이 붙지 않음
--   CONNECTED  폰 1대가 connect 완료. 이후 다른 기기의 connect 는 거부한다
--   CLOSED     PC 가 명시적으로 닫음. session_token_id 를 비워 폰 토큰도 함께 죽인다
-- 만료는 별도 상태가 아니라 expires_dttm 을 요청 시점에 비교해 판정한다.

CREATE TABLE ar_simulation_sessions (
    ar_session_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    session_id UUID NOT NULL,
    owner_seq INTEGER NOT NULL,
    status VARCHAR(10) NOT NULL DEFAULT 'CREATED',
    -- 발급된 sessionToken 의 jti. 세션을 닫으면 NULL 이 되어 JWT 만료 전에도 거부된다.
    session_token_id UUID,
    phone_connected_dttm TIMESTAMPTZ,
    composite_count SMALLINT NOT NULL DEFAULT 0,
    expires_dttm TIMESTAMPTZ NOT NULL,
    closed_dttm TIMESTAMPTZ,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_ar_simulation_sessions PRIMARY KEY (ar_session_seq),
    CONSTRAINT uq_ar_simulation_sessions_session_id UNIQUE (session_id),
    CONSTRAINT fk_ar_simulation_sessions_owner
        FOREIGN KEY (owner_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT ck_ar_simulation_sessions_status
        CHECK (status IN ('CREATED', 'CONNECTED', 'CLOSED')),
    CONSTRAINT ck_ar_simulation_sessions_composite_count
        CHECK (composite_count >= 0)
);

CREATE INDEX ix_ar_simulation_sessions_owner
    ON ar_simulation_sessions (owner_seq, reg_dttm DESC);

-- PC 가 미리 고른 도안. 폰 보관함 화면이 이 목록을 그대로 그린다.
CREATE TABLE ar_simulation_session_designs (
    ar_session_design_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ar_session_seq BIGINT NOT NULL,
    tattoo_seq BIGINT NOT NULL,
    sort_order SMALLINT NOT NULL,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_ar_simulation_session_designs PRIMARY KEY (ar_session_design_seq),
    CONSTRAINT uq_ar_simulation_session_designs UNIQUE (ar_session_seq, tattoo_seq),
    CONSTRAINT fk_ar_simulation_session_designs_session
        FOREIGN KEY (ar_session_seq)
        REFERENCES ar_simulation_sessions (ar_session_seq) ON DELETE CASCADE,
    CONSTRAINT fk_ar_simulation_session_designs_design
        FOREIGN KEY (tattoo_seq)
        REFERENCES tattoo_designs (tattoo_seq) ON DELETE RESTRICT,
    CONSTRAINT ck_ar_simulation_session_designs_sort_order
        CHECK (sort_order >= 0)
);

-- 폰이 찍어 올린 합성 결과. 이미지는 세션 소유자(PC 회원) 명의로 images 에 등록한다.
CREATE TABLE ar_simulation_composites (
    ar_composite_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ar_session_seq BIGINT NOT NULL,
    image_seq BIGINT NOT NULL,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_ar_simulation_composites PRIMARY KEY (ar_composite_seq),
    CONSTRAINT uq_ar_simulation_composites_image UNIQUE (image_seq),
    CONSTRAINT fk_ar_simulation_composites_session
        FOREIGN KEY (ar_session_seq)
        REFERENCES ar_simulation_sessions (ar_session_seq) ON DELETE CASCADE,
    CONSTRAINT fk_ar_simulation_composites_image
        FOREIGN KEY (image_seq) REFERENCES images (image_seq) ON DELETE RESTRICT
);

CREATE INDEX ix_ar_simulation_composites_session
    ON ar_simulation_composites (ar_session_seq, ar_composite_seq);
