-- Starttoo initial PostgreSQL schema.
-- Flyway가 빈 데이터베이스에 한 번 적용하는 생성 전용 마이그레이션이다.
--
-- pgvector 기능은 현재 비활성화되어 있다.
-- 사용을 시작할 때 확장, tattoo_embeddings 테이블, 벡터 인덱스의 주석을 해제한다.
-- CREATE EXTENSION IF NOT EXISTS vector;
--
-- tattoo_embeddings.embedding의 512차원은 임시값이다.
-- 실제 임베딩 모델을 확정한 뒤 VECTOR(512)를 해당 차원으로 변경한다.


-- =========================================================
-- 1. 회원·공통 이미지
-- users와 images의 순환 FK 중 profile_image_seq는 마지막에 연결한다.
-- =========================================================

CREATE TABLE users (
    user_seq INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nickname VARCHAR(20) NOT NULL,
    phone_number VARCHAR(16) NOT NULL,
    phone_verified_dttm TIMESTAMPTZ NOT NULL,
    profile_image_seq BIGINT,
    birth_date DATE,
    gender CHAR(1),
    role VARCHAR(10) NOT NULL DEFAULT 'USER',
    recent_search_terms VARCHAR(100)[] NOT NULL DEFAULT ARRAY[]::VARCHAR(100)[],
    account_status VARCHAR(12) NOT NULL DEFAULT 'ACTIVE',
    status_changed_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_usr_seq INTEGER,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_users PRIMARY KEY (user_seq),
    CONSTRAINT fk_users_mod_usr
        FOREIGN KEY (mod_usr_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT ck_users_nickname_length
        CHECK (char_length(nickname) BETWEEN 2 AND 20),
    CONSTRAINT ck_users_nickname_format
        CHECK (nickname ~ '^[가-힣A-Za-z0-9]+$'),
    CONSTRAINT ck_users_phone_number
        CHECK (phone_number ~ '^\+[1-9][0-9]{7,14}$'),
    CONSTRAINT ck_users_gender
        CHECK (gender IS NULL OR gender IN ('M', 'F')),
    CONSTRAINT ck_users_role
        CHECK (role IN ('USER', 'ARTIST', 'ADMIN')),
    CONSTRAINT ck_users_recent_search_terms
        CHECK (cardinality(recent_search_terms) <= 10),
    CONSTRAINT ck_users_account_status
        CHECK (account_status IN ('ACTIVE', 'SUSPENDED', 'BANNED', 'WITHDRAWN'))
);

CREATE TABLE images (
    image_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    object_key VARCHAR(512) NOT NULL,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reg_usr_seq INTEGER NOT NULL,
    mod_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_usr_seq INTEGER NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_images PRIMARY KEY (image_seq),
    CONSTRAINT uq_images_object_key UNIQUE (object_key),
    CONSTRAINT fk_images_reg_usr
        FOREIGN KEY (reg_usr_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_images_mod_usr
        FOREIGN KEY (mod_usr_seq) REFERENCES users (user_seq) ON DELETE RESTRICT
);

ALTER TABLE users
    ADD CONSTRAINT fk_users_profile_image
    FOREIGN KEY (profile_image_seq)
    REFERENCES images (image_seq)
    ON DELETE RESTRICT;


-- =========================================================
-- 2. 계정 상태·OAuth·인증·알림
-- =========================================================

CREATE TABLE user_account_status_histories (
    account_status_history_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_seq INTEGER NOT NULL,
    previous_status VARCHAR(12),
    changed_status VARCHAR(12) NOT NULL,
    reason_type VARCHAR(20) NOT NULL,
    reason_detail VARCHAR(1000),
    expired_dttm TIMESTAMPTZ,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reg_usr_seq INTEGER,

    CONSTRAINT pk_user_account_status_histories
        PRIMARY KEY (account_status_history_seq),
    CONSTRAINT fk_account_status_histories_user
        FOREIGN KEY (user_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_account_status_histories_reg_usr
        FOREIGN KEY (reg_usr_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT ck_account_histories_previous_status
        CHECK (
            previous_status IS NULL
            OR previous_status IN ('ACTIVE', 'SUSPENDED', 'BANNED', 'WITHDRAWN')
        ),
    CONSTRAINT ck_account_histories_changed_status
        CHECK (changed_status IN ('ACTIVE', 'SUSPENDED', 'BANNED', 'WITHDRAWN')),
    CONSTRAINT ck_account_histories_reason_type
        CHECK (
            reason_type IN (
                'SIGNUP',
                'USER_REQUEST',
                'POLICY_VIOLATION',
                'ADMIN_ACTION',
                'SUSPENSION_EXPIRED'
            )
        ),
    CONSTRAINT ck_account_histories_signup
        CHECK (
            (
                reason_type = 'SIGNUP'
                AND previous_status IS NULL
                AND changed_status = 'ACTIVE'
                AND reg_usr_seq IS NOT NULL
            )
            OR
            (
                reason_type <> 'SIGNUP'
                AND previous_status IS NOT NULL
            )
        ),
    CONSTRAINT ck_account_histories_actor
        CHECK (
            (
                reason_type = 'SUSPENSION_EXPIRED'
                AND changed_status = 'ACTIVE'
                AND reg_usr_seq IS NULL
            )
            OR
            (
                reason_type <> 'SUSPENSION_EXPIRED'
                AND reg_usr_seq IS NOT NULL
            )
        ),
    CONSTRAINT ck_account_histories_expiry
        CHECK (
            (
                changed_status = 'SUSPENDED'
                AND expired_dttm IS NOT NULL
            )
            OR
            (
                changed_status <> 'SUSPENDED'
                AND expired_dttm IS NULL
            )
        )
);

CREATE TABLE oauth_providers (
    oauth_provider_seq INTEGER GENERATED BY DEFAULT AS IDENTITY,
    provider_code VARCHAR(10) NOT NULL,
    provider_name VARCHAR(30) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reg_usr_seq INTEGER NOT NULL,
    mod_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_usr_seq INTEGER NOT NULL,

    CONSTRAINT pk_oauth_providers PRIMARY KEY (oauth_provider_seq),
    CONSTRAINT uq_oauth_providers_code UNIQUE (provider_code),
    CONSTRAINT fk_oauth_providers_reg_usr
        FOREIGN KEY (reg_usr_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_oauth_providers_mod_usr
        FOREIGN KEY (mod_usr_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT ck_oauth_providers_code
        CHECK (provider_code IN ('GOOGLE', 'KAKAO'))
);

CREATE TABLE user_oauth_accounts (
    user_oauth_account_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_seq INTEGER NOT NULL,
    oauth_provider_seq INTEGER NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    last_login_dttm TIMESTAMPTZ,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_user_oauth_accounts PRIMARY KEY (user_oauth_account_seq),
    CONSTRAINT fk_user_oauth_accounts_user
        FOREIGN KEY (user_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_user_oauth_accounts_provider
        FOREIGN KEY (oauth_provider_seq)
        REFERENCES oauth_providers (oauth_provider_seq)
        ON DELETE RESTRICT
);

CREATE TABLE user_devices (
    device_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_seq INTEGER NOT NULL,
    push_token VARCHAR(512) NOT NULL,
    platform VARCHAR(10) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_used_dttm TIMESTAMPTZ,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_user_devices PRIMARY KEY (device_seq),
    CONSTRAINT uq_user_devices_push_token UNIQUE (push_token),
    CONSTRAINT fk_user_devices_user
        FOREIGN KEY (user_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT ck_user_devices_platform
        CHECK (platform IN ('WEB', 'ANDROID', 'IOS'))
);

CREATE TABLE refresh_tokens (
    refresh_token_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_seq INTEGER NOT NULL,
    device_seq BIGINT,
    token_hash BYTEA NOT NULL,
    expires_dttm TIMESTAMPTZ NOT NULL,
    revoked_dttm TIMESTAMPTZ,
    last_used_dttm TIMESTAMPTZ,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_refresh_tokens PRIMARY KEY (refresh_token_seq),
    CONSTRAINT uq_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_refresh_tokens_device
        FOREIGN KEY (device_seq)
        REFERENCES user_devices (device_seq)
        ON DELETE RESTRICT,
    CONSTRAINT ck_refresh_tokens_hash_length
        CHECK (octet_length(token_hash) = 32),
    CONSTRAINT ck_refresh_tokens_expiry
        CHECK (expires_dttm > reg_dttm)
);

CREATE TABLE notifications (
    notification_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    receiver_seq INTEGER NOT NULL,
    actor_seq INTEGER,
    notification_type VARCHAR(20) NOT NULL,
    reference_seq BIGINT,
    title VARCHAR(100) NOT NULL,
    body VARCHAR(500) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    read_dttm TIMESTAMPTZ,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_notifications PRIMARY KEY (notification_seq),
    CONSTRAINT fk_notifications_receiver
        FOREIGN KEY (receiver_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_notifications_actor
        FOREIGN KEY (actor_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT ck_notifications_type
        CHECK (
            notification_type IN (
                'POST_LIKE',
                'POST_COMMENT',
                'COMMENT_LIKE',
                'FOLLOW',
                'SYSTEM'
            )
        ),
    CONSTRAINT ck_notifications_actor_reference
        CHECK (
            (
                notification_type IN (
                    'POST_LIKE',
                    'POST_COMMENT',
                    'COMMENT_LIKE',
                    'FOLLOW'
                )
                AND actor_seq IS NOT NULL
                AND reference_seq IS NOT NULL
            )
            OR
            (
                notification_type = 'SYSTEM'
                AND actor_seq IS NULL
            )
        ),
    CONSTRAINT ck_notifications_read
        CHECK (
            (is_read = TRUE AND read_dttm IS NOT NULL)
            OR
            (is_read = FALSE AND read_dttm IS NULL)
        )
);


-- =========================================================
-- 3. 아티스트·분류 마스터
-- =========================================================

CREATE TABLE artists (
    user_seq INTEGER NOT NULL,
    shop_name VARCHAR(100),
    shop_city VARCHAR(100),
    shop_address VARCHAR(255),
    shop_phone VARCHAR(30),
    shop_details VARCHAR(1000),
    verification_status VARCHAR(12) NOT NULL DEFAULT 'UNVERIFIED',
    rejection_reason VARCHAR(2000),
    verification_processed_dttm TIMESTAMPTZ,
    verification_processed_usr_seq INTEGER,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_usr_seq INTEGER NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_artists PRIMARY KEY (user_seq),
    CONSTRAINT fk_artists_user
        FOREIGN KEY (user_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_artists_mod_usr
        FOREIGN KEY (mod_usr_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_artists_verification_processed_usr
        FOREIGN KEY (verification_processed_usr_seq)
        REFERENCES users (user_seq)
        ON DELETE RESTRICT,
    CONSTRAINT ck_artists_verification_status
        CHECK (
            verification_status IN (
                'UNVERIFIED',
                'PENDING',
                'VERIFIED',
                'REJECTED'
            )
        ),
    CONSTRAINT ck_artists_verification_result
        CHECK (
            (
                verification_status = 'VERIFIED'
                AND verification_processed_dttm IS NOT NULL
                AND verification_processed_usr_seq IS NOT NULL
                AND rejection_reason IS NULL
            )
            OR
            (
                verification_status = 'REJECTED'
                AND verification_processed_dttm IS NOT NULL
                AND verification_processed_usr_seq IS NOT NULL
                AND rejection_reason IS NOT NULL
            )
            OR
            (
                verification_status IN ('UNVERIFIED', 'PENDING')
                AND verification_processed_dttm IS NULL
                AND verification_processed_usr_seq IS NULL
                AND rejection_reason IS NULL
            )
        )
);

CREATE TABLE primary_styles (
    primary_style_seq INTEGER GENERATED BY DEFAULT AS IDENTITY,
    style_code VARCHAR(30) NOT NULL,
    style_name VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reg_usr_seq INTEGER NOT NULL,
    mod_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_usr_seq INTEGER NOT NULL,

    CONSTRAINT pk_primary_styles PRIMARY KEY (primary_style_seq),
    CONSTRAINT uq_primary_styles_code UNIQUE (style_code),
    CONSTRAINT fk_primary_styles_reg_usr
        FOREIGN KEY (reg_usr_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_primary_styles_mod_usr
        FOREIGN KEY (mod_usr_seq) REFERENCES users (user_seq) ON DELETE RESTRICT
);

CREATE TABLE secondary_styles (
    secondary_style_seq INTEGER GENERATED BY DEFAULT AS IDENTITY,
    style_code VARCHAR(30) NOT NULL,
    style_name VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reg_usr_seq INTEGER NOT NULL,
    mod_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_usr_seq INTEGER NOT NULL,

    CONSTRAINT pk_secondary_styles PRIMARY KEY (secondary_style_seq),
    CONSTRAINT uq_secondary_styles_code UNIQUE (style_code),
    CONSTRAINT fk_secondary_styles_reg_usr
        FOREIGN KEY (reg_usr_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_secondary_styles_mod_usr
        FOREIGN KEY (mod_usr_seq) REFERENCES users (user_seq) ON DELETE RESTRICT
);

CREATE TABLE rendering_styles (
    rendering_style_seq INTEGER GENERATED BY DEFAULT AS IDENTITY,
    style_code VARCHAR(30) NOT NULL,
    style_name VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reg_usr_seq INTEGER NOT NULL,
    mod_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_usr_seq INTEGER NOT NULL,

    CONSTRAINT pk_rendering_styles PRIMARY KEY (rendering_style_seq),
    CONSTRAINT uq_rendering_styles_code UNIQUE (style_code),
    CONSTRAINT fk_rendering_styles_reg_usr
        FOREIGN KEY (reg_usr_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_rendering_styles_mod_usr
        FOREIGN KEY (mod_usr_seq) REFERENCES users (user_seq) ON DELETE RESTRICT
);

CREATE TABLE colors (
    color_seq INTEGER GENERATED BY DEFAULT AS IDENTITY,
    color_code VARCHAR(30) NOT NULL,
    color_name VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reg_usr_seq INTEGER NOT NULL,
    mod_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_usr_seq INTEGER NOT NULL,

    CONSTRAINT pk_colors PRIMARY KEY (color_seq),
    CONSTRAINT uq_colors_code UNIQUE (color_code),
    CONSTRAINT fk_colors_reg_usr
        FOREIGN KEY (reg_usr_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_colors_mod_usr
        FOREIGN KEY (mod_usr_seq) REFERENCES users (user_seq) ON DELETE RESTRICT
);

CREATE TABLE subjects (
    subject_seq INTEGER GENERATED BY DEFAULT AS IDENTITY,
    subject_name VARCHAR(50) NOT NULL,

    CONSTRAINT pk_subjects PRIMARY KEY (subject_seq),
    CONSTRAINT uq_subjects_name UNIQUE (subject_name)
);


-- =========================================================
-- 4. 타투·도안·개인화
-- =========================================================

CREATE TABLE tattoos (
    tattoo_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    registrant_seq INTEGER NOT NULL,
    image_seq BIGINT NOT NULL,
    source_type VARCHAR(20) NOT NULL,
    primary_style_seq INTEGER NOT NULL,
    secondary_style_1_seq INTEGER,
    secondary_style_2_seq INTEGER,
    rendering_style_1_seq INTEGER,
    rendering_style_2_seq INTEGER,
    color_seq INTEGER,
    is_used_for_training BOOLEAN NOT NULL DEFAULT FALSE,
    trained_dttm TIMESTAMPTZ,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_tattoos PRIMARY KEY (tattoo_seq),
    CONSTRAINT uq_tattoos_image UNIQUE (image_seq),
    CONSTRAINT fk_tattoos_registrant
        FOREIGN KEY (registrant_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_tattoos_image
        FOREIGN KEY (image_seq) REFERENCES images (image_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_tattoos_primary_style
        FOREIGN KEY (primary_style_seq)
        REFERENCES primary_styles (primary_style_seq)
        ON DELETE RESTRICT,
    CONSTRAINT fk_tattoos_secondary_style_1
        FOREIGN KEY (secondary_style_1_seq)
        REFERENCES secondary_styles (secondary_style_seq)
        ON DELETE RESTRICT,
    CONSTRAINT fk_tattoos_secondary_style_2
        FOREIGN KEY (secondary_style_2_seq)
        REFERENCES secondary_styles (secondary_style_seq)
        ON DELETE RESTRICT,
    CONSTRAINT fk_tattoos_rendering_style_1
        FOREIGN KEY (rendering_style_1_seq)
        REFERENCES rendering_styles (rendering_style_seq)
        ON DELETE RESTRICT,
    CONSTRAINT fk_tattoos_rendering_style_2
        FOREIGN KEY (rendering_style_2_seq)
        REFERENCES rendering_styles (rendering_style_seq)
        ON DELETE RESTRICT,
    CONSTRAINT fk_tattoos_color
        FOREIGN KEY (color_seq) REFERENCES colors (color_seq) ON DELETE RESTRICT,
    CONSTRAINT ck_tattoos_source_type
        CHECK (source_type IN ('DEFAULT', 'USER_POST', 'USER_COLLECTION')),
    CONSTRAINT ck_tattoos_secondary_order
        CHECK (
            secondary_style_2_seq IS NULL
            OR secondary_style_1_seq IS NOT NULL
        ),
    CONSTRAINT ck_tattoos_secondary_distinct
        CHECK (
            secondary_style_1_seq IS NULL
            OR secondary_style_2_seq IS NULL
            OR secondary_style_1_seq <> secondary_style_2_seq
        ),
    CONSTRAINT ck_tattoos_rendering_order
        CHECK (
            rendering_style_2_seq IS NULL
            OR rendering_style_1_seq IS NOT NULL
        ),
    CONSTRAINT ck_tattoos_rendering_distinct
        CHECK (
            rendering_style_1_seq IS NULL
            OR rendering_style_2_seq IS NULL
            OR rendering_style_1_seq <> rendering_style_2_seq
        ),
    CONSTRAINT ck_tattoos_training
        CHECK (
            (is_used_for_training = TRUE AND trained_dttm IS NOT NULL)
            OR
            (is_used_for_training = FALSE AND trained_dttm IS NULL)
        )
);

CREATE TABLE tattoo_subjects (
    tattoo_seq BIGINT NOT NULL,
    subject_seq INTEGER NOT NULL,

    CONSTRAINT pk_tattoo_subjects PRIMARY KEY (tattoo_seq, subject_seq),
    CONSTRAINT fk_tattoo_subjects_tattoo
        FOREIGN KEY (tattoo_seq) REFERENCES tattoos (tattoo_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_tattoo_subjects_subject
        FOREIGN KEY (subject_seq) REFERENCES subjects (subject_seq) ON DELETE RESTRICT
);

CREATE TABLE tattoo_designs (
    tattoo_seq BIGINT NOT NULL,
    image_seq BIGINT NOT NULL,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_tattoo_designs PRIMARY KEY (tattoo_seq),
    CONSTRAINT uq_tattoo_designs_image UNIQUE (image_seq),
    CONSTRAINT fk_tattoo_designs_tattoo
        FOREIGN KEY (tattoo_seq) REFERENCES tattoos (tattoo_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_tattoo_designs_image
        FOREIGN KEY (image_seq) REFERENCES images (image_seq) ON DELETE RESTRICT
);

/*
CREATE TABLE tattoo_embeddings (
    tattoo_embedding_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tattoo_seq BIGINT NOT NULL,
    embedding_model_code VARCHAR(100) NOT NULL,
    embedding VECTOR(512) NOT NULL,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tattoo_embeddings PRIMARY KEY (tattoo_embedding_seq),
    CONSTRAINT uq_tattoo_embeddings_tattoo_model
        UNIQUE (tattoo_seq, embedding_model_code),
    CONSTRAINT fk_tattoo_embeddings_tattoo
        FOREIGN KEY (tattoo_seq)
        REFERENCES tattoos (tattoo_seq)
        ON DELETE CASCADE
);
*/

CREATE TABLE user_primary_style_preferences (
    user_seq INTEGER NOT NULL,
    primary_style_seq INTEGER NOT NULL,
    score NUMERIC(10,4) NOT NULL DEFAULT 0,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_user_primary_style_preferences
        PRIMARY KEY (user_seq, primary_style_seq),
    CONSTRAINT fk_user_primary_preferences_user
        FOREIGN KEY (user_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_user_primary_preferences_style
        FOREIGN KEY (primary_style_seq)
        REFERENCES primary_styles (primary_style_seq)
        ON DELETE RESTRICT
);

CREATE TABLE user_color_preferences (
    user_seq INTEGER NOT NULL,
    color_seq INTEGER NOT NULL,
    score NUMERIC(10,4) NOT NULL DEFAULT 0,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_user_color_preferences PRIMARY KEY (user_seq, color_seq),
    CONSTRAINT fk_user_color_preferences_user
        FOREIGN KEY (user_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_user_color_preferences_color
        FOREIGN KEY (color_seq) REFERENCES colors (color_seq) ON DELETE RESTRICT
);

CREATE TABLE tattoo_collections (
    collection_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_seq INTEGER NOT NULL,
    tattoo_seq BIGINT NOT NULL,
    body_view VARCHAR(10) NOT NULL,
    position_x DOUBLE PRECISION NOT NULL,
    position_y DOUBLE PRECISION NOT NULL,
    scale_ratio DOUBLE PRECISION NOT NULL,
    rotation_degree DOUBLE PRECISION NOT NULL,
    is_flipped BOOLEAN NOT NULL DEFAULT FALSE,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_tattoo_collections PRIMARY KEY (collection_seq),
    CONSTRAINT uq_tattoo_collections_tattoo UNIQUE (tattoo_seq),
    CONSTRAINT fk_tattoo_collections_user
        FOREIGN KEY (user_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_tattoo_collections_tattoo
        FOREIGN KEY (tattoo_seq) REFERENCES tattoos (tattoo_seq) ON DELETE RESTRICT,
    CONSTRAINT ck_tattoo_collections_body_view
        CHECK (body_view <> ''),
    CONSTRAINT ck_tattoo_collections_position_x
        CHECK (position_x BETWEEN 0 AND 1),
    CONSTRAINT ck_tattoo_collections_position_y
        CHECK (position_y BETWEEN 0 AND 1),
    CONSTRAINT ck_tattoo_collections_scale_ratio
        CHECK (scale_ratio > 0),
    CONSTRAINT ck_tattoo_collections_rotation_degree
        CHECK (rotation_degree BETWEEN -180 AND 180)
);

CREATE TABLE user_archive (
    user_seq INTEGER NOT NULL,
    tattoo_seq BIGINT NOT NULL,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_user_archive PRIMARY KEY (user_seq, tattoo_seq),
    CONSTRAINT fk_user_archive_user
        FOREIGN KEY (user_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_user_archive_tattoo_design
        FOREIGN KEY (tattoo_seq)
        REFERENCES tattoo_designs (tattoo_seq)
        ON DELETE RESTRICT
);


-- =========================================================
-- 5. 소셜 관계
-- =========================================================

CREATE TABLE user_follows (
    follower_seq INTEGER NOT NULL,
    following_seq INTEGER NOT NULL,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_user_follows PRIMARY KEY (follower_seq, following_seq),
    CONSTRAINT fk_user_follows_follower
        FOREIGN KEY (follower_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_user_follows_following
        FOREIGN KEY (following_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT ck_user_follows_distinct
        CHECK (follower_seq <> following_seq)
);

CREATE TABLE user_blocks (
    blocker_seq INTEGER NOT NULL,
    blocked_seq INTEGER NOT NULL,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_user_blocks PRIMARY KEY (blocker_seq, blocked_seq),
    CONSTRAINT fk_user_blocks_blocker
        FOREIGN KEY (blocker_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_user_blocks_blocked
        FOREIGN KEY (blocked_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT ck_user_blocks_distinct
        CHECK (blocker_seq <> blocked_seq)
);


-- =========================================================
-- 6. 게시물·댓글·반응·신고
-- =========================================================

CREATE TABLE posts (
    post_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    author_seq INTEGER NOT NULL,
    content VARCHAR(3000),
    post_status VARCHAR(12) NOT NULL DEFAULT 'PUBLISHED',
    like_count INTEGER NOT NULL DEFAULT 0,
    comment_count INTEGER NOT NULL DEFAULT 0,
    report_count INTEGER NOT NULL DEFAULT 0,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_usr_seq INTEGER NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_posts PRIMARY KEY (post_seq),
    CONSTRAINT fk_posts_author
        FOREIGN KEY (author_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_posts_mod_usr
        FOREIGN KEY (mod_usr_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT ck_posts_status
        CHECK (post_status IN ('PUBLISHED', 'HIDDEN', 'DELETED')),
    CONSTRAINT ck_posts_counts
        CHECK (like_count >= 0 AND comment_count >= 0 AND report_count >= 0),
    CONSTRAINT ck_posts_status_deleted
        CHECK (
            (post_status = 'DELETED' AND is_deleted = TRUE)
            OR
            (post_status IN ('PUBLISHED', 'HIDDEN') AND is_deleted = FALSE)
        )
);

CREATE TABLE post_images (
    post_image_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    post_seq BIGINT NOT NULL,
    image_seq BIGINT NOT NULL,
    display_order SMALLINT NOT NULL,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_post_images PRIMARY KEY (post_image_seq),
    CONSTRAINT uq_post_images_image UNIQUE (image_seq),
    CONSTRAINT uq_post_images_post_order UNIQUE (post_seq, display_order),
    CONSTRAINT fk_post_images_post
        FOREIGN KEY (post_seq) REFERENCES posts (post_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_post_images_image
        FOREIGN KEY (image_seq) REFERENCES images (image_seq) ON DELETE RESTRICT,
    CONSTRAINT ck_post_images_display_order
        CHECK (display_order > 0)
);

CREATE TABLE comments (
    comment_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    post_seq BIGINT NOT NULL,
    author_seq INTEGER NOT NULL,
    parent_comment_seq BIGINT,
    content VARCHAR(1000) NOT NULL,
    like_count INTEGER NOT NULL DEFAULT 0,
    comment_status VARCHAR(12) NOT NULL DEFAULT 'PUBLISHED',
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_usr_seq INTEGER NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_comments PRIMARY KEY (comment_seq),
    CONSTRAINT uq_comments_post_comment UNIQUE (post_seq, comment_seq),
    CONSTRAINT fk_comments_post
        FOREIGN KEY (post_seq) REFERENCES posts (post_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_comments_author
        FOREIGN KEY (author_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_comments_parent_same_post
        FOREIGN KEY (post_seq, parent_comment_seq)
        REFERENCES comments (post_seq, comment_seq)
        ON DELETE RESTRICT,
    CONSTRAINT fk_comments_mod_usr
        FOREIGN KEY (mod_usr_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT ck_comments_parent_not_self
        CHECK (parent_comment_seq IS NULL OR parent_comment_seq <> comment_seq),
    CONSTRAINT ck_comments_like_count
        CHECK (like_count >= 0),
    CONSTRAINT ck_comments_status
        CHECK (comment_status IN ('PUBLISHED', 'HIDDEN', 'DELETED')),
    CONSTRAINT ck_comments_status_deleted
        CHECK (
            (comment_status = 'DELETED' AND is_deleted = TRUE)
            OR
            (comment_status IN ('PUBLISHED', 'HIDDEN') AND is_deleted = FALSE)
        )
);

CREATE TABLE comment_likes (
    comment_seq BIGINT NOT NULL,
    user_seq INTEGER NOT NULL,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_comment_likes PRIMARY KEY (comment_seq, user_seq),
    CONSTRAINT fk_comment_likes_comment
        FOREIGN KEY (comment_seq) REFERENCES comments (comment_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_comment_likes_user
        FOREIGN KEY (user_seq) REFERENCES users (user_seq) ON DELETE RESTRICT
);

CREATE TABLE post_likes (
    post_seq BIGINT NOT NULL,
    user_seq INTEGER NOT NULL,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_post_likes PRIMARY KEY (post_seq, user_seq),
    CONSTRAINT fk_post_likes_post
        FOREIGN KEY (post_seq) REFERENCES posts (post_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_post_likes_user
        FOREIGN KEY (user_seq) REFERENCES users (user_seq) ON DELETE RESTRICT
);

CREATE TABLE post_bookmarks (
    post_seq BIGINT NOT NULL,
    user_seq INTEGER NOT NULL,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_post_bookmarks PRIMARY KEY (post_seq, user_seq),
    CONSTRAINT fk_post_bookmarks_post
        FOREIGN KEY (post_seq) REFERENCES posts (post_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_post_bookmarks_user
        FOREIGN KEY (user_seq) REFERENCES users (user_seq) ON DELETE RESTRICT
);

CREATE TABLE post_hidden_preferences (
    post_seq BIGINT NOT NULL,
    user_seq INTEGER NOT NULL,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_post_hidden_preferences PRIMARY KEY (post_seq, user_seq),
    CONSTRAINT fk_post_hidden_preferences_post
        FOREIGN KEY (post_seq) REFERENCES posts (post_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_post_hidden_preferences_user
        FOREIGN KEY (user_seq) REFERENCES users (user_seq) ON DELETE RESTRICT
);

CREATE TABLE post_reports (
    report_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    post_seq BIGINT NOT NULL,
    reporter_seq INTEGER NOT NULL,
    reason_code VARCHAR(30) NOT NULL,
    reason_detail VARCHAR(1000),
    report_status VARCHAR(12) NOT NULL DEFAULT 'PENDING',
    processing_note VARCHAR(1000),
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_usr_seq INTEGER NOT NULL,

    CONSTRAINT pk_post_reports PRIMARY KEY (report_seq),
    CONSTRAINT uq_post_reports_post_reporter UNIQUE (post_seq, reporter_seq),
    CONSTRAINT fk_post_reports_post
        FOREIGN KEY (post_seq) REFERENCES posts (post_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_post_reports_reporter
        FOREIGN KEY (reporter_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_post_reports_mod_usr
        FOREIGN KEY (mod_usr_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT ck_post_reports_status
        CHECK (report_status IN ('PENDING', 'ACCEPTED', 'REJECTED')),
    CONSTRAINT ck_post_reports_processing
        CHECK (
            (
                report_status = 'PENDING'
                AND processing_note IS NULL
                AND mod_usr_seq = reporter_seq
            )
            OR
            (
                report_status IN ('ACCEPTED', 'REJECTED')
                AND mod_usr_seq IS NOT NULL
            )
        )
);


-- =========================================================
-- 7. 1대1 DM
-- dm_messages와 dm_room_participants의 순환 FK는 마지막에 완성한다.
-- =========================================================

CREATE TABLE dm_rooms (
    dm_room_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user1_seq INTEGER NOT NULL,
    user2_seq INTEGER NOT NULL,
    last_message_dttm TIMESTAMPTZ,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_dm_rooms PRIMARY KEY (dm_room_seq),
    CONSTRAINT uq_dm_rooms_users UNIQUE (user1_seq, user2_seq),
    CONSTRAINT fk_dm_rooms_user1
        FOREIGN KEY (user1_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_dm_rooms_user2
        FOREIGN KEY (user2_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT ck_dm_rooms_user_order
        CHECK (user1_seq < user2_seq)
);

CREATE TABLE dm_room_participants (
    dm_room_seq BIGINT NOT NULL,
    user_seq INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_notification_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_hidden_message_seq BIGINT,
    last_left_dttm TIMESTAMPTZ,

    CONSTRAINT pk_dm_room_participants PRIMARY KEY (dm_room_seq, user_seq),
    CONSTRAINT fk_dm_room_participants_room
        FOREIGN KEY (dm_room_seq)
        REFERENCES dm_rooms (dm_room_seq)
        ON DELETE RESTRICT,
    CONSTRAINT fk_dm_room_participants_user
        FOREIGN KEY (user_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT ck_dm_room_participants_left
        CHECK (is_active = TRUE OR last_left_dttm IS NOT NULL)
);

CREATE TABLE dm_messages (
    dm_message_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
    dm_room_seq BIGINT NOT NULL,
    sender_seq INTEGER NOT NULL,
    message_type VARCHAR(20) NOT NULL,
    text_content VARCHAR(4000),
    image_seq BIGINT,
    read_dttm TIMESTAMPTZ,
    reg_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_dttm TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_usr_seq INTEGER NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_dm_messages PRIMARY KEY (dm_message_seq),
    CONSTRAINT uq_dm_messages_room_message
        UNIQUE (dm_room_seq, dm_message_seq),
    CONSTRAINT fk_dm_messages_room
        FOREIGN KEY (dm_room_seq)
        REFERENCES dm_rooms (dm_room_seq)
        ON DELETE RESTRICT,
    CONSTRAINT fk_dm_messages_sender
        FOREIGN KEY (dm_room_seq, sender_seq)
        REFERENCES dm_room_participants (dm_room_seq, user_seq)
        ON DELETE RESTRICT,
    CONSTRAINT fk_dm_messages_image
        FOREIGN KEY (image_seq) REFERENCES images (image_seq) ON DELETE RESTRICT,
    CONSTRAINT fk_dm_messages_mod_usr
        FOREIGN KEY (mod_usr_seq) REFERENCES users (user_seq) ON DELETE RESTRICT,
    CONSTRAINT ck_dm_messages_type
        CHECK (message_type IN ('TEXT', 'IMAGE', 'TEXT_WITH_IMAGE')),
    CONSTRAINT ck_dm_messages_content
        CHECK (
            (
                message_type = 'TEXT'
                AND text_content IS NOT NULL
                AND image_seq IS NULL
            )
            OR
            (
                message_type = 'IMAGE'
                AND text_content IS NULL
                AND image_seq IS NOT NULL
            )
            OR
            (
                message_type = 'TEXT_WITH_IMAGE'
                AND text_content IS NOT NULL
                AND image_seq IS NOT NULL
            )
        ),
    CONSTRAINT ck_dm_messages_deleted_modifier
        CHECK (
            (is_deleted = FALSE AND mod_usr_seq = sender_seq)
            OR
            (is_deleted = TRUE AND mod_usr_seq IS NOT NULL)
        )
);

ALTER TABLE dm_room_participants
    ADD CONSTRAINT fk_dm_room_participants_last_hidden_message
    FOREIGN KEY (dm_room_seq, last_hidden_message_seq)
    REFERENCES dm_messages (dm_room_seq, dm_message_seq)
    ON DELETE RESTRICT;

-- =========================================================
-- 8. 주요 조회 인덱스
-- =========================================================

CREATE UNIQUE INDEX uq_users_active_nickname
    ON users (nickname)
    WHERE is_deleted = FALSE;

CREATE UNIQUE INDEX uq_users_active_phone_number
    ON users (phone_number)
    WHERE is_deleted = FALSE;

CREATE UNIQUE INDEX uq_user_oauth_accounts_active_provider_subject
    ON user_oauth_accounts (oauth_provider_seq, provider_subject)
    WHERE is_deleted = FALSE;

CREATE UNIQUE INDEX uq_user_oauth_accounts_active_user_provider
    ON user_oauth_accounts (user_seq, oauth_provider_seq)
    WHERE is_deleted = FALSE;

CREATE INDEX idx_users_status_deleted
    ON users (account_status, is_deleted);

CREATE INDEX idx_account_status_histories_user_dttm
    ON user_account_status_histories (user_seq, reg_dttm DESC);

CREATE INDEX idx_tattoos_primary_deleted_dttm
    ON tattoos (primary_style_seq, is_deleted, reg_dttm);

CREATE INDEX idx_tattoos_color_deleted_dttm
    ON tattoos (color_seq, is_deleted, reg_dttm);

CREATE INDEX idx_tattoos_registrant_deleted_dttm
    ON tattoos (registrant_seq, is_deleted, reg_dttm);

CREATE INDEX idx_tattoo_subjects_subject_tattoo
    ON tattoo_subjects (subject_seq, tattoo_seq);

CREATE INDEX idx_artists_verification_user
    ON artists (verification_status, user_seq);

CREATE INDEX idx_artists_city_verification_user
    ON artists (shop_city, verification_status, user_seq);

CREATE INDEX idx_posts_status_deleted_dttm
    ON posts (post_status, is_deleted, reg_dttm DESC);

CREATE INDEX idx_posts_author_deleted_dttm
    ON posts (author_seq, is_deleted, reg_dttm DESC);

CREATE INDEX idx_comments_post_parent_deleted_dttm
    ON comments (post_seq, parent_comment_seq, is_deleted, reg_dttm);

CREATE INDEX idx_post_reports_status_dttm
    ON post_reports (report_status, reg_dttm);

CREATE INDEX idx_notifications_receiver_read_dttm
    ON notifications (receiver_seq, is_read, reg_dttm DESC);

CREATE INDEX idx_user_blocks_blocked_blocker
    ON user_blocks (blocked_seq, blocker_seq);

CREATE INDEX idx_user_follows_following_follower
    ON user_follows (following_seq, follower_seq);

CREATE INDEX idx_dm_room_participants_user_active_room
    ON dm_room_participants (user_seq, is_active, dm_room_seq);

/*
CREATE INDEX idx_tattoo_embeddings_hnsw
    ON tattoo_embeddings
    USING hnsw (embedding vector_cosine_ops);
*/
