spring:
  config:
    activate:
      on-profile: local

app:
  firebase:
    enabled: false
  ai:
    enabled: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    com.starttoo.backend: DEBUG
